[build]
  command = ""
  publish = "."

[[redirects]]
  from = "/about"
  to = "/generic.html"
  status = 200

[[redirects]]
  from = "/experience"
  to = "/elements.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/projects.html"
  status = 200

[[redirects]]
  from = "/InsideGrid"
  to = "/insidegrid.html"
  status = 200

[[redirects]]
  from = "/insidegrid"
  to = "/InsideGrid"
  status = 301
  force = true

[[redirects]]
  from = "/fashion"
  to = "/freakyfashion.html"
  status = 200

[[redirects]]
  from = "/freakyfashion"
  to = "/fashion"
  status = 301
  force = true

[[redirects]]
  from = "/shotgun"
  to = "/shotgun/index.html"
  status = 200

[[redirects]]
  from = "/blackjack"
  to = "/demos/index.html"
  status = 200

[[redirects]]
  from = "/northwind"
  to = "/demos/index.html"
  status = 200

[[redirects]]
  from = "/bank-api"
  to = "/demos/index.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/demos/index.html"
  status = 200

[[redirects]]
  from = "/address-book"
  to = "/demos/index.html"
  status = 200

[[redirects]]
  from = "/address-book-group"
  to = "/demos/index.html"
  status = 200

[[redirects]]
  from = "/crypto-portfolio"
  to = "/demos/index.html"
  status = 200

[[redirects]]
  from = "/python-chat"
  to = "/demos/index.html"
  status = 200

[[redirects]]
  from = "/python-lab"
  to = "/demos/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/cv"
  to = "/cv.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/generic"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/generic.html"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/elements"
  to = "/experience"
  status = 301
  force = true

[[redirects]]
  from = "/elements.html"
  to = "/experience"
  status = 301
  force = true

[[redirects]]
  from = "/projects.html"
  to = "/projects"
  status = 301
  force = true

[[redirects]]
  from = "/contact.html"
  to = "/contact"
  status = 301
  force = true

[[redirects]]
  from = "/cv.html"
  to = "/cv"
  status = 301
  force = true

[[redirects]]
  from = "/privacy.html"
  to = "/privacy"
  status = 301
  force = true
