const app=document.querySelector('#app');
const route=new URLSearchParams(window.location.search).get('project')||window.location.pathname.replace(/^\/+|\/+$/g,'')||'projects';
const pexels={
  python:{src:'/assets/media/projects/pexels/python-programming.jpg',url:'https://www.pexels.com/photo/woman-programming-on-a-notebook-1181359/',alt:'Developer programming on a laptop'},
  cards:{src:'/assets/media/projects/pexels/playing-cards.jpg',url:'https://www.pexels.com/photo/playing-cards-5477760/',alt:'Playing cards on a dark surface'},
  crypto:{src:'/assets/media/projects/pexels/crypto-dashboard.jpg',url:'https://www.pexels.com/photo/cryptocurrency-chart-displayed-on-a-laptop-14751274/',alt:'Cryptocurrency charts on a laptop'}
};
const meta={
  blackjack:{name:'Blackjack',theme:'blackjack',tech:'Python · Flask · Sessions',repo:'blackjack.py',title:'Play the hand.\n<em>Know when to stand.</em>',copy:'A browser edition of the original Flask learning project, rebuilt for instant play under Patricia’s domain.',media:pexels.cards},
  northwind:{name:'Northwind',theme:'northwind',tech:'C# · Razor Pages · EF Core · SQL Server',repo:'NorthwindApp',title:'Product data,\n<em>made useful.</em>',copy:'Explore a browser demo based on the original Northwind product list and detail pages.',media:pexels.python},
  'bank-api':{name:'Stanca Bank',theme:'bank',tech:'ASP.NET Core · EF Core · JWT · SQL Server',repo:'StancaBankApi',title:'Secure flows.\n<em>Clear finances.</em>',copy:'An interactive frontend demonstration of the account, transaction and role flows implemented by the original API.',media:pexels.crypto},
  blog:{name:'Stanca Journal',theme:'blog',tech:'ASP.NET Core · EF Core · JWT · OpenAPI',repo:'StancaBlogApi',title:'Ideas deserve\n<em>good structure.</em>',copy:'A publication-style frontend demo for the blog posts, categories and comments supported by the original API.',media:pexels.python},
  'address-book':{name:'AddressBook',theme:'address',tech:'C# · .NET · Avalonia UI',repo:'AddressBookAvalonia',title:'People, details,\n<em>one calm place.</em>',copy:'A browser interpretation of the original cross-platform Avalonia contact manager.',media:pexels.python},
  'address-book-group':{name:'AddressBook Team',theme:'group',tech:'C# · .NET · Avalonia UI · Git',repo:'AddressBookAvaloniaGroup',title:'Shared contacts.\n<em>Stronger teamwork.</em>',copy:'A collaborative contact workspace inspired by the group-built Avalonia application.',media:pexels.python},
  'crypto-portfolio':{name:'Crypto Portfolio',theme:'crypto',tech:'Python · SQLite · Click · CoinGecko API',repo:'sqlite3',title:'Track the position.\n<em>See the value.</em>',copy:'A visual companion to the original command-line portfolio manager, using local sample prices rather than claiming live market data.',media:pexels.crypto},
  'python-chat':{name:'Python Chat',theme:'chat',tech:'Python · Tkinter · MongoDB',repo:'python_chatt',title:'Small messages.\n<em>Simple persistence.</em>',copy:'A browser demo of the message flow from the original Tkinter and MongoDB learning project.',media:pexels.python},
  'python-lab':{name:'Python Lab',theme:'python',tech:'Python · Tkinter · Flask · Pygame',repo:'Projects_py',title:'Learn by making.\n<em>One script at a time.</em>',copy:'A playful browser collection inspired by the original Python GUI, Flask and Pygame exercises.',media:pexels.python}
};
const project=meta[route]||meta['python-lab'];
document.body.className=`theme-${project.theme}`;
document.title=`${project.name} | Patricia Stanca`;
document.querySelector('meta[name="description"]').content=project.copy;
document.querySelector('#brand-name').textContent=project.name;
document.querySelector('#footer-tech').textContent=project.tech;
document.querySelector('#source-link').href=`https://github.com/PatriciaStanca/${project.repo}`;

function mediaMarkup(media){return media?`<figure class="hero-media"><img src="${media.src}" alt="${media.alt}"><figcaption class="photo-credit">Photo: <a href="${media.url}">Pexels</a></figcaption></figure>`:`<div class="hero-media" aria-hidden="true"></div>`;}
function shell(workspace){app.innerHTML=`<div class="shell"><section class="hero"><div><p class="eyebrow">${project.name} · Live project</p><h1>${project.title.replace('\n','<br>')}</h1><p class="hero-copy">${project.copy}</p></div>${mediaMarkup(project.media)}</section>${workspace}</div>`;}
function workspace(title,body,notice='Interactive portfolio demo · Data is stored only in this browser session.'){return `<section class="workspace"><header class="workspace-bar"><span class="workspace-title">${title}</span><span class="status">Ready</span></header><div class="workspace-body"><p class="notice">${notice}</p>${body}</div></section>`;}

function setupBlackjack(){
  shell(workspace('Blackjack table',`<div class="blackjack"><div class="table"><div><span class="score" id="dealer-score">Dealer · ?</span><div class="hand" id="dealer-hand"></div></div><div><span class="score" id="player-score">You · 0</span><div class="hand" id="player-hand"></div></div></div><aside class="game-panel"><p class="eyebrow">Private table</p><h2 id="game-state">Place your bet.</h2><p id="game-copy">Get as close to 21 as possible without going over.</p><div class="game-actions"><button class="primary" id="deal">Deal cards</button><button class="secondary" id="hit" disabled>Hit</button><button class="secondary" id="stand" disabled>Stand</button></div></aside></div>`,'Playable browser edition · No money, account or server is involved.'));
  const suits=['♥','♦','♣','♠'];const ranks=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];let playerHand=[];let dealerHand=[];let active=false;
  const card=()=>({rank:ranks[Math.floor(Math.random()*ranks.length)],suit:suits[Math.floor(Math.random()*suits.length)]});
  const score=hand=>{let total=hand.reduce((sum,c)=>sum+(c.rank==='A'?11:['K','Q','J'].includes(c.rank)?10:Number(c.rank)),0);let aces=hand.filter(c=>c.rank==='A').length;while(total>21&&aces--)total-=10;return total;};
  const cards=hand=>hand.map(c=>`<div class="playing-card ${['♥','♦'].includes(c.suit)?'red':''}"><span>${c.rank}</span><b>${c.suit}</b></div>`).join('');
  const render=(hideDealer=true)=>{document.querySelector('#player-hand').innerHTML=cards(playerHand);document.querySelector('#dealer-hand').innerHTML=hideDealer&&active?cards([dealerHand[0]])+'<div class="playing-card"><b>?</b></div>':cards(dealerHand);document.querySelector('#player-score').textContent=`You · ${score(playerHand)}`;document.querySelector('#dealer-score').textContent=`Dealer · ${hideDealer&&active?'?':score(dealerHand)}`;};
  const finish=()=>{active=false;while(score(dealerHand)<17)dealerHand.push(card());const p=score(playerHand),d=score(dealerHand);document.querySelector('#game-state').textContent=p>21?'Bust.':d>21||p>d?'You win.':p===d?'Push.':'Dealer wins.';document.querySelector('#game-copy').textContent=`Final score: you ${p}, dealer ${d}.`;document.querySelector('#hit').disabled=true;document.querySelector('#stand').disabled=true;document.querySelector('#deal').textContent='Deal again';render(false);};
  document.querySelector('#deal').addEventListener('click',()=>{playerHand=[card(),card()];dealerHand=[card(),card()];active=true;document.querySelector('#game-state').textContent='Your move.';document.querySelector('#game-copy').textContent='Hit for another card or stand with this hand.';document.querySelector('#hit').disabled=false;document.querySelector('#stand').disabled=false;render();if(score(playerHand)===21)finish();});
  document.querySelector('#hit').addEventListener('click',()=>{playerHand.push(card());render();if(score(playerHand)>=21)finish();});document.querySelector('#stand').addEventListener('click',finish);
}

const products=[['1','Chai','Beverages','18.00','39'],['2','Chang','Beverages','19.00','17'],['4','Chef Anton’s Cajun Seasoning','Condiments','22.00','53'],['11','Queso Cabrales','Dairy Products','21.00','22'],['17','Alice Mutton','Meat/Poultry','39.00','0'],['24','Guaraná Fantástica','Beverages','4.50','20'],['31','Gorgonzola Telino','Dairy Products','12.50','0'],['40','Boston Crab Meat','Seafood','18.40','123']];
function setupNorthwind(){shell(workspace('Product explorer',`<div class="toolbar"><input class="field" id="product-search" type="search" placeholder="Search products"><select class="field" id="category-filter"><option value="">All categories</option><option>Beverages</option><option>Condiments</option><option>Dairy Products</option><option>Meat/Poultry</option><option>Seafood</option></select></div><div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Product</th><th>Category</th><th>Price</th><th>Stock</th></tr></thead><tbody id="product-rows"></tbody></table></div>`,'Browser demonstration using representative Northwind sample records.'));
 const render=()=>{const q=document.querySelector('#product-search').value.toLowerCase(),cat=document.querySelector('#category-filter').value;document.querySelector('#product-rows').innerHTML=products.filter(p=>p[1].toLowerCase().includes(q)&&(!cat||p[2]===cat)).map(p=>`<tr><td>${p[0]}</td><td><strong>${p[1]}</strong></td><td><span class="tag">${p[2]}</span></td><td>$${p[3]}</td><td>${p[4]}</td></tr>`).join('')||'<tr><td colspan="5">No matching products.</td></tr>';};document.querySelector('#product-search').addEventListener('input',render);document.querySelector('#category-filter').addEventListener('change',render);render();}

function setupBank(){shell(workspace('Customer dashboard',`<div class="cards"><article class="card"><small>Total balance</small><div class="metric" id="total-balance">64,280 kr</div><p>Across two accounts</p></article><article class="card"><small>Everyday account</small><h3>24,280 kr</h3><p>•• 4821</p></article><article class="card"><small>Savings</small><h3 id="savings-balance">40,000 kr</h3><p>•• 1740</p></article></div><form class="toolbar" id="transfer-form" style="margin-top:22px"><select class="field" id="transfer-from"><option value="everyday">Everyday account</option><option value="savings">Savings</option></select><input class="field" id="transfer-amount" type="number" min="1" max="10000" placeholder="Amount in SEK" required><button class="primary" type="submit">Transfer</button></form><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Description</th><th>Account</th><th>Amount</th></tr></thead><tbody id="bank-rows"><tr><td>Today</td><td>Opening demo balance</td><td>Everyday</td><td>24,280 kr</td></tr></tbody></table></div>`,'Frontend demonstration · No real bank connection, credentials or transactions.'));
 let everyday=24280,savings=40000;document.querySelector('#transfer-form').addEventListener('submit',event=>{event.preventDefault();const amount=Number(document.querySelector('#transfer-amount').value);const from=document.querySelector('#transfer-from').value;if(!amount||amount<1)return;if(from==='everyday'&&amount<=everyday){everyday-=amount;savings+=amount;}else if(from==='savings'&&amount<=savings){savings-=amount;everyday+=amount;}else return;document.querySelector('#total-balance').textContent=`${(everyday+savings).toLocaleString('sv-SE')} kr`;document.querySelector('#savings-balance').textContent=`${savings.toLocaleString('sv-SE')} kr`;document.querySelector('#bank-rows').insertAdjacentHTML('afterbegin',`<tr><td>Now</td><td>Demo transfer</td><td>${from==='everyday'?'Everyday → Savings':'Savings → Everyday'}</td><td>${amount.toLocaleString('sv-SE')} kr</td></tr>`);event.target.reset();});}

const posts=[{title:'Designing APIs people can trust',cat:'Development',text:'Clear contracts, predictable status codes and ownership rules make an API easier to use and safer to maintain.'},{title:'What data modelling changes',cat:'Data',text:'A thoughtful model turns scattered records into information that teams can actually reason about.'},{title:'Learning in public, building with care',cat:'Process',text:'Small projects create room to test decisions, document lessons and improve the next implementation.'}];
function setupBlog(){shell(workspace('Latest stories',`<div class="toolbar"><button class="secondary active" data-category="">All</button><button class="secondary" data-category="Development">Development</button><button class="secondary" data-category="Data">Data</button><button class="secondary" data-category="Process">Process</button></div><div class="cards" id="post-grid"></div>`,'Editorial frontend demonstration · Posts are representative portfolio copy.'));const render=cat=>{document.querySelector('#post-grid').innerHTML=posts.filter(p=>!cat||p.cat===cat).map((p,i)=>`<article class="card"><small>${p.cat} · 0${i+1}</small><h3>${p.title}</h3><p>${p.text}</p></article>`).join('');};document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.category);}));render('');}

const contacts=[{name:'Maya Lind',role:'Product designer',email:'maya@example.com',phone:'+46 70 123 45 67'},{name:'Jonas Berg',role:'Backend developer',email:'jonas@example.com',phone:'+46 73 987 65 43'},{name:'Sara Holm',role:'Data analyst',email:'sara@example.com',phone:'+46 72 555 18 20'}];
function contactView(team=false){return `<div class="split"><aside class="sidebar"><div class="toolbar"><input class="field" id="contact-search" type="search" placeholder="Search people"></div><div class="list" id="contact-list"></div></aside><section class="content-pane"><p class="eyebrow">${team?'Shared workspace':'Contact details'}</p><h2 id="contact-name">Select a contact</h2><p id="contact-role">Choose someone from the list to view their information.</p><div class="cards" id="contact-details"></div>${team?'<button class="primary" id="team-note" type="button">Add collaboration note</button>':''}</section></div>`;}
function setupAddress(team=false){shell(`<section class="workspace"><header class="workspace-bar"><span class="workspace-title">${team?'Team directory':'My contacts'}</span><span class="status">Local demo</span></header>${contactView(team)}</section>`);const list=document.querySelector('#contact-list');const render=q=>{list.innerHTML=contacts.filter(c=>c.name.toLowerCase().includes(q)).map((c,i)=>`<button type="button" data-contact="${i}"><span class="avatar">${c.name.split(' ').map(x=>x[0]).join('')}</span><strong>${c.name}</strong></button>`).join('');list.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>select(Number(b.dataset.contact),b)));};const select=(i,b)=>{const c=contacts[i];list.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#contact-name').textContent=c.name;document.querySelector('#contact-role').textContent=c.role;document.querySelector('#contact-details').innerHTML=`<article class="card"><small>Email</small><h3>${c.email}</h3></article><article class="card"><small>Phone</small><h3>${c.phone}</h3></article>${team?'<article class="card"><small>Team</small><h3>Product delivery</h3></article>':''}`;};document.querySelector('#contact-search').addEventListener('input',e=>render(e.target.value.toLowerCase()));render('');list.querySelector('button')?.click();if(team)document.querySelector('#team-note').addEventListener('click',event=>{event.currentTarget.textContent='Collaboration note added ✓';});}

function setupCrypto(){shell(workspace('Portfolio overview',`<div class="cards"><article class="card"><small>Sample portfolio value</small><div class="metric" id="portfolio-value">$0.00</div><p>Calculated locally</p></article><article class="card"><small>Bitcoin sample price</small><h3>$62,450</h3><p>Fixed demonstration value</p></article><article class="card"><small>Ethereum sample price</small><h3>$3,280</h3><p>Fixed demonstration value</p></article></div><form class="toolbar" id="crypto-form" style="margin-top:22px"><select class="field" id="coin"><option value="62450">Bitcoin</option><option value="3280">Ethereum</option><option value="142">Solana</option></select><input class="field" id="amount" type="number" min="0" step="0.001" placeholder="Coin amount" required><button class="primary" type="submit">Calculate</button></form><div class="console" id="crypto-console">$ python main_2.py get-investment-value\nReady for a local calculation…</div>`,'Portfolio calculator · Prices are fixed examples, not live financial data or advice.'));document.querySelector('#crypto-form').addEventListener('submit',event=>{event.preventDefault();const amount=Number(document.querySelector('#amount').value),select=document.querySelector('#coin'),value=amount*Number(select.value);document.querySelector('#portfolio-value').textContent=value.toLocaleString('en-US',{style:'currency',currency:'USD'});document.querySelector('#crypto-console').textContent=`$ calculate --coin=${select.options[select.selectedIndex].text.toLowerCase()} --amount=${amount}\nPortfolio value: ${value.toFixed(2)} USD\nSaved to this browser session only.`;});}

function setupChat(){shell(workspace('Message room',`<div class="chat"><div class="messages" id="messages"><div class="message">Welcome to the browser version of Python Chat.</div><div class="message mine">Messages stay on this page only.</div></div><form class="composer" id="chat-form"><input class="field" id="chat-input" maxlength="180" placeholder="Write a message" required><button class="primary" type="submit">Send</button></form></div>`,'Local message demonstration · Nothing is sent to MongoDB or another person.'));document.querySelector('#chat-form').addEventListener('submit',event=>{event.preventDefault();const input=document.querySelector('#chat-input'),message=document.createElement('div');message.className='message mine';message.textContent=input.value;document.querySelector('#messages').append(message);input.value='';message.scrollIntoView({behavior:'smooth'});});}

function setupPythonLab(){shell(workspace('Learning playground',`<div class="lab-tabs"><button class="secondary" data-lab="form">Tkinter form</button><button class="secondary" data-lab="game">Pygame chase</button><button class="secondary" data-lab="routes">Flask routes</button></div><div class="lab-stage" id="lab-stage"></div>`,'Browser interpretations of the original learning scripts.'));const stage=document.querySelector('#lab-stage');let timer;const open=name=>{clearInterval(timer);if(name==='form'){stage.innerHTML='<form class="form-grid" id="lab-form"><label>Name<input class="field" required></label><label>Favourite language<select class="field"><option>Python</option><option>JavaScript</option><option>C#</option></select></label><label class="wide"><span>Newsletter</span><select class="field"><option>Yes, please</option><option>Not now</option></select></label><button class="primary wide" type="submit">Submit locally</button><p class="wide" id="form-result"></p></form>';stage.querySelector('form').addEventListener('submit',e=>{e.preventDefault();stage.querySelector('#form-result').textContent='Form submitted in the browser ✓';});}else if(name==='routes'){stage.innerHTML='<p class="eyebrow">Flask route map</p><div class="endpoint-list"><div class="endpoint"><span class="method">GET</span><strong>/</strong><span class="tag">index.html</span></div><div class="endpoint"><span class="method">GET</span><strong>/about</strong><span class="tag">about.html</span></div><div class="endpoint"><span class="method">GET</span><strong>/contact</strong><span class="tag">response</span></div></div>';}else{stage.innerHTML='<p class="eyebrow">Use arrow keys to evade</p><div class="player-dot" id="player-dot"></div><div class="enemy-dot" style="left:10%;top:25%"></div><div class="enemy-dot" style="left:78%;top:20%"></div><div class="enemy-dot" style="left:20%;top:76%"></div>';let player={x:48,y:46};const move=e=>{if(e.key==='ArrowLeft')player.x-=3;if(e.key==='ArrowRight')player.x+=3;if(e.key==='ArrowUp')player.y-=3;if(e.key==='ArrowDown')player.y+=3;player.x=Math.max(0,Math.min(94,player.x));player.y=Math.max(8,Math.min(90,player.y));const dot=document.querySelector('#player-dot');if(dot){dot.style.left=`${player.x}%`;dot.style.top=`${player.y}%`;}};document.onkeydown=move;timer=setInterval(()=>document.querySelectorAll('.enemy-dot').forEach(enemy=>{const x=parseFloat(enemy.style.left),y=parseFloat(enemy.style.top);enemy.style.left=`${x+(x<player.x?1:-1)}%`;enemy.style.top=`${y+(y<player.y?1:-1)}%`;}),120);}};document.querySelectorAll('[data-lab]').forEach(button=>button.addEventListener('click',()=>open(button.dataset.lab)));open('form');}

({blackjack:setupBlackjack,northwind:setupNorthwind,'bank-api':setupBank,blog:setupBlog,'address-book':()=>setupAddress(false),'address-book-group':()=>setupAddress(true),'crypto-portfolio':setupCrypto,'python-chat':setupChat,'python-lab':setupPythonLab}[route]||setupPythonLab)();
